---
apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    app: demo
spec:
  containers:
  - name: demo
    image: gcr.io/stable-vista-418814/mock_webserver:2.0.0
    ports:
    - name: http
      containerPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 10
      timeoutSeconds: 5
      periodSeconds: 10
      failureThreshold: 2