---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
  - name: redis
    image: redis
    env:
    - name: REDIS_USERNAME
      valueFrom:
        secretKeyRef:
          name: redis-secret
          key: username
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: redis-secret
          key: password